[metadata]
name = rss2email
version = attr: rss2email.__version__
description = A python script that converts RSS/Atom newsfeeds to email
long_description = file: README.rst
author = Adam Mokhtari, W. Trevor King, Amir Yalon
author_email = 2553423+uutari@users.noreply.github.com, wking@tremily.us, git@please.nospammail.net
maintainer = Adam Mokhtari
maintainer_email = 2553423+uutari@users.noreply.github.com
license = GPL-2.0-or-later
keywords = rss, atom, feed, email
classifiers =
    Development Status :: 5 - Production/Stable
    Environment :: Console
    Intended Audience :: End Users/Desktop
    Operating System :: OS Independent
    Programming Language :: Python
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.6
    Programming Language :: Python :: 3.7
    Programming Language :: Python :: 3.8
    Programming Language :: Python :: 3.9
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.11
    Topic :: Communications :: Email
    Topic :: Software Development :: Libraries :: Python Modules
project_urls =
    Homepage = https://github.com/rss2email/rss2email
    Repository = https://github.com/rss2email/rss2email
    Bug Tracker = https://github.com/rss2email/rss2email/issues

[options]
python_requires = >=3.6
install_requires =
    feedparser>=6.0.5
    html2text>=2020.1.16
packages = find:

[options.extras_require]
dev =
    update-copyright>=0.6.2

[options.entry_points]
console_scripts =
    r2e = rss2email.main:run

[options.packages.find]
where = .